### ISSUE TITLE
Error en hash para verificación de pago.

### ISSUE THREAD

**Issue by LeoVsYou** [wompisv/wocommerce-wompi-sv-plugin#2]
En la URL de respuesta se ha introducido un cambio en la generación del HASH ya que al parecer no se puede validar de la siguiente manera: (wocommerce-wompi-sv-plugin/wc-WOMPI-payment.php:110)
$cadena = $order_id . $idTransaccion . $idEnlace . $monto;
$sig = hash_hmac('sha256', $cadena, $this->client_secret);

Esto porque en los últimos pagos que se han realizado en la información de la orden registra: "wompi hash no valido" y en la tienda no se redirige correctamente al cliente a la orden.

**Comment by wompisv** [comment]
> En la URL de respuesta se ha introducido un cambio en la generación del HASH ya que al parecer no se puede validar de la siguiente manera: (wocommerce-wompi-sv-plugin/wc-WOMPI-payment.php:110)
> $cadena = $order_id . $idTransaccion . $idEnlace . $monto;
> $sig = hash_hmac('sha256', $cadena, $this->client_secret);
> 
> Esto porque en los últimos pagos que se han realizado en la información de la orden registra: "wompi hash no valido" y en la tienda no se redirige correctamente al cliente a la orden.

Este error solo sucede con algunos servidores que por alguna razón no recuperan toda la información dentro del body del webhook. Estrañamente el hash dentro del body, se omite y por eso se generaba el error de hash no válido. Esto se solventó en la versión 1.2.2
